name: Auto-Commit

on:
  schedule:
    - cron: '0 */10 * * *'  # Каждые 10 часов (в 00:00, 10:00, 20:00 UTC)
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Git
        run: |
          git config user.name "Auto Committer"
          git config user.email "auto-committer@users.noreply.github.com"
          
      - name: Generate commit
        run: |
          # Проверяем изменения
          if git diff-index --quiet HEAD --; then
            echo "No changes detected. Creating empty commit..."
            git commit --allow-empty -m "Auto-commit: Empty commit to keep app awake"
          else
            echo "Changes detected. Creating regular commit..."
            echo "Update: $(date)" >> auto-update.txt
            git add .
            git commit -m "Auto-commit: $(date)"
          fi
          
      - name: Push changes
        run: git push
